
package Gui;


public class VentanaPrincipal extends javax.swing.JFrame {

    private Object model;


    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        panelCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelFilters = new javax.swing.JPanel();
        lblFrom = new javax.swing.JLabel();
        dateFrom = new com.toedter.calendar.JDateChooser();
        lblTo = new javax.swing.JLabel();
        dateTo = new com.toedter.calendar.JDateChooser();
        btnSearch = new javax.swing.JButton();
        panelStatus = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        panelTitle.setBackground(new java.awt.Color(51, 102, 255));
        panelTitle.setForeground(new java.awt.Color(0, 0, 0));
        panelTitle.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        panelTitle.setName("pnlTitle"); // NOI18N

        lblTitle.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("SMARTOCUPATION - GESTIÓN DE ALQUILERES");
        lblTitle.setToolTipText("");

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Expediente", "Cliente", "Casa", "FechaEntrada", "Meses", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lblFrom.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        lblFrom.setText("From:");
        panelFilters.add(lblFrom);
        panelFilters.add(dateFrom);

        lblTo.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblTo.setText("To:");
        panelFilters.add(lblTo);
        panelFilters.add(dateTo);

        btnSearch.setBackground(new java.awt.Color(255, 204, 51));
        btnSearch.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(0, 0, 0));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        panelFilters.add(btnSearch);

        javax.swing.GroupLayout panelCenterLayout = new javax.swing.GroupLayout(panelCenter);
        panelCenter.setLayout(panelCenterLayout);
        panelCenterLayout.setHorizontalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCenterLayout.createSequentialGroup()
                .addComponent(panelFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCenterLayout.setVerticalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCenterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelFilters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        panelStatus.setBackground(new java.awt.Color(102, 255, 255));

        lblStatus.setBackground(new java.awt.Color(204, 255, 204));
        lblStatus.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(0, 0, 0));
        lblStatus.setText("Listo para buscar Alquileres");
        lblStatus.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout panelStatusLayout = new javax.swing.GroupLayout(panelStatus);
        panelStatus.setLayout(panelStatusLayout);
        panelStatusLayout.setHorizontalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStatusLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(lblStatus)
                .addGap(34, 34, 34))
        );
        panelStatusLayout.setVerticalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStatusLayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(panelCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(panelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorAdded
         try {
        // Obtener fechas seleccionadas
        java.util.Date fechaDesde = dateFrom.getDate();
        java.util.Date fechaHasta = dateTo.getDate();
        
        // Validar fechas
        if (fechaDesde == null || fechaHasta == null) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Por favor, seleccione ambas fechas", 
                "Fechas requeridas", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (fechaDesde.after(fechaHasta)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "La fecha 'Desde' no puede ser posterior a la fecha 'Hasta'", 
                "Fechas inválidas", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
          
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Error al buscar alquileres: " + e.getMessage(), 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jPanel1AncestorAdded

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
         try {
        // Obtener fechas seleccionadas
        java.util.Date fechaDesde = dateFrom.getDate();
        java.util.Date fechaHasta = dateTo.getDate();
        
        // Validar fechas
        if (fechaDesde == null || fechaHasta == null) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Por favor, seleccione ambas fechas", 
                "Fechas requeridas", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (fechaDesde.after(fechaHasta)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "La fecha 'Desde' no puede ser posterior a la fecha 'Hasta'", 
                "Fechas inválidas", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 3. BUSCAR EN BASE DE DATOS REAL (CAMBIO PRINCIPAL)
          Dao.AlquilerBD alquilerBD = new Dao.AlquilerBD(); 
        java.util.List<model.Alquiler> alquileres = 
            alquilerBD.buscarAlquileresPorFecha(fechaDesde, fechaHasta);
        
        // 4. Actualizar tabla
        actualizarTabla(alquileres);
        
        // 5. Actualizar estado
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        String mensaje = "<html><div style='text-align: center;'>"
               + "Encontrados " + alquileres.size() + " alquileres<br>"
               + "entre " + sdf.format(fechaDesde) + " y " + sdf.format(fechaHasta)
               + "</div></html>";

        lblStatus.setText(mensaje);
        this.pack();
            
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Error al buscar alquileres: " + e.getMessage(), 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSearchActionPerformed

private void actualizarTabla(java.util.List<model.Alquiler> alquileres) {
    // Crear datos para la tabla
    Object[][] datos = new Object[alquileres.size()][6];
    
    java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("dd/MM/yyyy");
    
    for (int i = 0; i < alquileres.size(); i++) {
        model.Alquiler a = alquileres.get(i);
        datos[i][0] = a.getNumeroExpediente();
        datos[i][1] = a.getCliente().getNombre();
        datos[i][2] = a.getCasa().getCodigoReferencia(); 
        datos[i][3] = dateFormat.format(a.getFechaEntrada());
        datos[i][4] = a.getTiempoEstimadoMeses();
        datos[i][5] = a.getEstado();
    }
    // Nombres de columnas
    String[] columnas = {"Expediente", "Cliente", "Vivienda", "Fecha Entrada", "Meses", "Estado"};
    
    // Crear nuevo modelo de tabla
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(datos, columnas) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Hacer la tabla no editable
        }
    };
    
    jTable1.setModel(model);
    jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
    jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 400));
}
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private com.toedter.calendar.JDateChooser dateFrom;
    private com.toedter.calendar.JDateChooser dateTo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTo;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelFilters;
    private javax.swing.JPanel panelStatus;
    private javax.swing.JPanel panelTitle;
    // End of variables declaration//GEN-END:variables
}
